version: "3.8"
services:
  nuruja:
    build: .
    container_name: nuruja
    command: gunicorn wsgi:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/nuruja
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      - nuruja-db

  nuruja-db:
    image: postgres:latest
    container_name: nuruja-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  admin:
    image: adminer
    container_name: admin
    restart: always
    depends_on:
      - nuruja-db
    ports:
      - "8080:8080"

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - nuruja
