"""removed category and shelf tables

Revision ID: 9489b9380176
Revises: fdd0e107ae31
Create Date: 2023-06-21 11:16:42.504436

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9489b9380176'
down_revision = 'fdd0e107ae31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelf')
    op.drop_table('category')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('book_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('book_category_id_fkey', 'category', ['category_id'], ['id'])

    op.create_table('category',
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('category_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='category_pkey'),
    sa.UniqueConstraint('name', name='category_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('shelf',
    sa.Column('floor', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='shelf_book_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='shelf_pkey')
    )
    # ### end Alembic commands ###
